# Default, Defaults
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
<<<<<<< HEAD
 
# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
>>>>>>> f2b1d416370c7584dac2e60ebbd577ebb8d6e181

# Jekyll Defaults
title: Loui's Record
email: gjsgud2@gmail.com
description: Loui's CS History. Algorithm, Data Mining, Game, Etc...
encoding: UTF-8
baseurl: ""

# Where can people find your site?
url: "https://suyeony0.github.io"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: Nina Petropoulos
authorBio: A English major by day, a musician by night, and a web developer because of the summer I was bored - my name's Nina and I hope you enjoy my Hello Portland theme, the second theme I've made with Jekyll.
